/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hardwarestock;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author ls
 */
public class AddPC extends javax.swing.JPanel {

    /**
     * Creates new form AddPC
     */
    public AddPC() {
        initComponents();
    }
    
//    public void addAccount() throws SQLException {
//        try {
//            DBConn dbc = new DBConn();
//            Connection conn = dbc.dbConnection();
//            String s = "INSERT into UserAccounts (Username,Password,Status) VALUES (?,?,'Offline')";
//            PreparedStatement ps = conn.prepareStatement(s);
//            ps.setString(1, jTextField1.getText());
//            ps.setString(2, jPasswordField1.getText()); 
//            ps.executeUpdate();
//
//            jTextField1.setText("");
//            jPasswordField1.setText("");
//            jPasswordField2.setText("");
//
//            jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ebsw/images/success.png")));
//
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(null, e);
//            e.printStackTrace();
//        }
//
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
