/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hardwarestock;

import java.awt.Container;
import java.util.Vector;
import hardwarestock.DBConn;
import java.awt.Dimension;
import java.nio.channels.SelectableChannel;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ls
 */
public class RoomPanel extends javax.swing.JPanel {

    /**
     * Creates new form RoomPanel
     */
    private Vector<Vector<String>> data; //used for data from database
    private Vector<String> header; //used to store data header

    public RoomPanel(String roomSelected) {
        //rpPanel.setText(roomSelected);
        try {
            data = getPcInfo("select * from PC where room_No = '" + roomSelected + "'");
            //create header for the table
            header = new Vector<String>();
            //header.add("Room Number"); //Empid
            header.add("PC ID"); // employee name
            header.add("PC name");
            header.add("CPU");
            header.add("Motherboard");
            header.add("GPU");
            header.add("Memory");
            header.add("Storage");
            header.add("NIC");
            initComponents();
            rpPanel.setText("Room: " + roomSelected);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public Vector getPcInfo(String s) throws Exception {

        Vector<Vector<String>> roomVector = new Vector<Vector<String>>();
        Connection con = new DBConn().dbConnection();
        PreparedStatement ps = con.prepareStatement(s);
        ResultSet rs = ps.executeQuery();

        while (rs.next()) {
            Vector<String> room = new Vector<String>();
            //room.add(rs.getString("room_no")); //Empid
            room.add(rs.getString("pc_id")); //name
            room.add(rs.getString("pcname"));
            room.add(rs.getString("cpu"));
            room.add(rs.getString("mobo"));
            room.add(rs.getString("gpu"));
            room.add(rs.getString("memory"));
            room.add(rs.getString("storage"));
            room.add(rs.getString("network_Card"));

            roomVector.add(room);
        }

        /*Close the connection after use (MUST)*/
        if (con != null) {
            con.close();
        }

        return roomVector;
    }
    
//    public void update() {
//        jTable1.removeAll();
//        try {
////            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
////            String url = "jdbc:odbc:Driver={Microsoft Access Driver "
////                    + "(*.mdb, *.accdb)};DBQ=C:\\NetbeansProject\\AccessDB\\HardwareStock.accdb";
////            Connection con = DriverManager.getConnection(url);
////            String url = "jdbc:ucanaccess://T:/(software)/HardwareStock/AccessDB/HardwareStock.accdb";
////            Connection con = DriverManager.getConnection(url);
//            Connection con = new DBConn().dbConnection();
//            Statement stmt = null;
//            ResultSet rs = null;
//
//            // SQL query command
//            String SQL = "SELECT * FROM ROOM";
//            stmt = con.createStatement();
//            rs = stmt.executeQuery(SQL);
//            while (rs.next()) {
//                roomCombo.addItem(rs.getString("room_No"));
//            }
//            con.close();
//        } catch (SQLException e) {
//            System.out.println("SQL Exception: " + e.toString());
//        } catch (Exception e) {
//            System.out.println("Exception: " + e);
//        }
//    }

//    public void addAccount() throws SQLException {
//        try {
//            DBConn dbc = new DBConn();
//            Connection conn = dbc.dbConnection();
//            String s = "INSERT into UserAccounts (Username,Password,Status) VALUES (?,?,'Offline')";
//            PreparedStatement ps = conn.prepareStatement(s);
//            ps.setString(1, jTextField1.getText());
//            ps.setString(2, jPasswordField1.getText()); 
//            ps.executeUpdate();
//
//            jTextField1.setText("");
//            jPasswordField1.setText("");
//            jPasswordField2.setText("");
//
//            jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ebsw/images/success.png")));
//
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(null, e);
//            e.printStackTrace();
//        }
//
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        rpPanel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        addPCButton = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        rpPanel.setText("jLabel1");
        jPanel1.add(rpPanel);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        addPCButton.setText("Add PC");
        addPCButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPCButtonActionPerformed(evt);
            }
        });
        jPanel2.add(addPCButton);

        jButton6.setText("Modify");
        jPanel2.add(jButton6);

        jButton7.setText("Delete");
        jPanel2.add(jButton7);

        jButton8.setText("Return to main menu");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton8);

        add(jPanel2, java.awt.BorderLayout.PAGE_END);

        jPanel3.setLayout(new java.awt.BorderLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            data, header
        ));
        jScrollPane2.setViewportView(jTable1);

        jPanel3.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        add(jPanel3, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        new MainMenu().setVisible(true);
        javax.swing.SwingUtilities.getWindowAncestor(this).dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void addPCButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPCButtonActionPerformed
        // TODO add your handling code here:
//       jTable1.remove();
    }//GEN-LAST:event_addPCButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addPCButton;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel rpPanel;
    // End of variables declaration//GEN-END:variables
}
